### PR TITLE
Link State 2017 changes

### PR DESCRIPTION
**Pull request by ramon349**
-made changes required to display link state 2017 
- updated IEE president info

### CODE REVIEW

**Comment by brenns10** [comment]
I don't think you committed the IEEE changes

**Comment by brenns10** [comment]
Or changes to 2017.haml

**Comment by ramon349** [comment]
My bad. will merge this one then add actual changes to the 2017 HAML and IEE section

**Comment by ajm188** [comment]
In the future, you can just push more commits to the branch, rather than opening multiple PRs :)

**Comment by brenns10** [comment]
Yeah, we already discussed offline :)

**Comment by ramon349** [comment]
yeah multiple PR's got really difficult to handle. I know better now.

**Pull request merged**
