### PR TITLE
CSS Security -> Certified Security Solutions

### PR DESCRIPTION
**Pull request by brenns10**
Hi @StephHippo

### CODE REVIEW

**Comment by brenns10** [comment]
Bye @StephHippo

**Comment by ajm188** [comment]
CSS Security -> Certified Security Solutions Security ?

**Comment by ajm188** [comment]
Ah I actually looked at the diff. Don't mind me 😲

**Comment by brenns10** [comment]
Don't spam a conference organizer with notifications. It doesn't help our sanity :P

**Pull request merged**
