### PR TITLE
Readme deploy instructions

### PR DESCRIPTION
**Pull request by matthewbentley**
Note that the official acm docker server documentation has yet to be written.  If we need more detailed instructions, let me know and I'll expand it a bit.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
The documentation should give someone who magically received access to the correct machine(s) to be able to complete a deploy with your instructions and reasonable basic knowledge. Having the proper Docker information would help greatly.

**Comment by StephHippo** [comment]
Will test out this documentation tonight or tomorrow.

**Comment by thomasrussellmurphy** [comment]
Note: these instructions currently appear to have no basis in the current reality of deploying.

Currently:
```
sudo su cabal
~cabal/update.sh
exit  # or Ctrl-D
sudo service cabal restart
```
Should complete a deploy. Do *NOT* use the sometimes-provided `update-cabal.sh` script, it won't work.

**Comment by thomasrussellmurphy** [comment]
Update:

```
sudo su cabal
~cabal/update.sh
cd
cd cabal/
# Edit `Gemfile` to comment out `ruby 2.2.1` line. `vim` is an available text editor.
bundle
exit  # or Ctrl-D
sudo service cabal restart
```

Things are broken, yo.

**Comment by matthewbentley** [comment]
Closing, since I should write better documentation.

**Pull request closed without merging**
