### PR TITLE
Add Facebook event and Eventbrite.

### PR DESCRIPTION
**Pull request by brenns10**
Also adds a slightly expanded intro paragraph and sets the time to be 7:00 AM - 5:00 PM (which we can change if necessary).

### CODE REVIEW

**Comment by brenns10** [comment]
verbal :+1: from @matthewbentley

**Comment by brenns10** [comment]
And deployed - http://acm.case.edu/acm/conference/2016

**Comment by matthewbentley** [comment]
Oh no I gave him too much power.

**Comment by brenns10** [comment]
I think you mean "finally, one less person bugging me to deploy the site"

**Pull request merged**
