### PR TITLE
Update meta tag in 2016 page.

### PR DESCRIPTION
**Pull request by brenns10**
Noticed a bug in the "description" that Slack posted when you send this link.  I just adjusted it to be up-to-date for 2016.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
+1, excessive copypasta that one time.

**Comment by ajm188** [comment]
Holy crap, how did this fall through the cracks? Oops :stuck_out_tongue:

**Comment by thomasrussellmurphy** [comment]
Not yet deployed. Docker builds are being really slow.

**Comment by thomasrussellmurphy** [comment]
Deployed successfully.

**Pull request merged**
