### PR TITLE
Add initial code of conduct for LinkState.

### PR DESCRIPTION
**Pull request by brenns10**
Comments on this are very much encouraged.  What I have here is adapted from [this](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy) wiki page about anti-harassment policies (found that page from the PyCon [code of conduct](https://github.com/python/pycon-code-of-conduct/blob/master/code_of_conduct.md)).

Since the original is more targeted to anti-harassment topics, I tried to make this a bit more general sounding, while still including plenty of anti-harassment language, mostly so we could feel confident that this policy would clearly restrict behavior we've had in the past that was less than satisfactory.

Comments and suggestions very welcome.

### CODE REVIEW

**Comment by ajm188** [comment]
Might also want to add that since we are a CWRU organization, Case harrassment policies are also in effect

**Comment by thomasrussellmurphy** [comment]
Also, since we encompass both the ACM and IEEE, references to their codes of conduct as professional organizations would be relevant.

**Comment by matthewbentley** [comment]
Link to CWRU policies: https://students.case.edu/handbook/policy/
ACM Code of Ethics and Professional Conduct: http://www.acm.org/about-acm/acm-code-of-ethics-and-professional-conduct
IEEE Code of Conduct: http://www.ieee.org/about/ieee_code_of_conduct.pdf

**Comment by brenns10** [comment]
PR updated with the suggested policies from above.

**Comment by helloleah** [comment]
Looks good to me; I don't have anything to add at this time. :grapes:

**Comment by StephHippo** [comment]
Not on current exec but I appreciate this being taken seriously and implementing a policy with enforcement.

**Comment by ajm188** [comment]
"not on current exec" != "cannot give input"

if you have suggestions/edits, we'd love to hear them!
sincerely,
Not an Exec :stuck_out_tongue_winking_eye:

**Comment by DLance96** [comment]
:+1:

**Comment by timtadh** [comment]
@brenns10 I like it. I also like http://abstractions.io/policies/#code-of-conduct . It has a section specifically about sponsors which is important. Check it out (it is similar).

**Comment by brenns10** [comment]
@timtadh: Are you talking about this section?

> We won't treat people as second-class undesireables because they're non-mainstream or might frighten sponsors. We care about our sponsors, but our attendees are who we do this for. To us, you're not eyeballs. You're not supportive tweets. You're not demographic groups. You're people.

Because we have the part saying that this anti-harassment policy applies to sponsors too.

**Comment by timtadh** [comment]
@brenns10 oh! never mind i missed it. Everything looks good! :+1:

**Comment by timtadh** [comment]
Maybe we should also put this on the wiki? hacsoc.org/wiki ?

**Comment by brenns10** [comment]
@timtadh: I was thinking of putting together a more generic one to put on the wiki for HacSoc in general.  But I thought that one might need to be discussed on hackers-discuss, because it would apply  to things like Wednesday night talks, GB meetings, etc.  I'll file an issue on hacsoc/wiki for a more general code of conduct, and since it looks like we have approval here, I'll merge this so I can move on with Mozilla.

**Comment by timtadh** [comment]
@brenns10 ++ on discussing it on hackers-discuss but let's try to have the actual discussion on github. so make that clear in the email or it could be flame fest.

**Pull request merged**
