### PR TITLE
updated speakers

### PR DESCRIPTION
**Pull request by ramon349**
A few issues: 
   1. Link for sponsor logo isn't working. Not really sure what the cause is. 
   2. Speaker bio's need to be reformatted. i'll merge once formating is done

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
I've cleaned up the formatting and switched to sponsor rendering code that gets the links working.

**Comment by brenns10** [comment]
Looks like a solid speaker schedule! Everything works on my machine, thanks for the help, @thomasrussellmurphy. The only thing I would say is that, comparing Freenome's logo to Covermymeds, it looks very small since it is not very wide. I see a [photo](https://www.freenome.com/contact/) on their site which uses a logo + company name wide format, similar to the wide logo covermymeds has on the site. We want to make sure our sponsors have roughly equal representation and brand recognition, since their funding the conference. Maybe @JDulin can hook us up with the wide graphic?

Beyond that, looks good to ship. @ramon349, let me know if / when you want me to merge+deploy and I'll do so. We can handle the logo in a separate branch.

**Comment by JDulin** [comment]
Thanks for the ping @brenns10!  Investigating with our recruiting & marketing departments...

**Comment by JDulin** [comment]
@ramon349 Looking at the email Brian sent you on 9/25, he forwarded a vector image to you.  This is a rasterized image in this PR.  You should be able to resize the `svg` he sent you to anything you want.

**Comment by brenns10** [comment]
A picture is worth a thousand words here.

screenshot_20170928_222231

We can definitely resize the circular logo to be bigger, but then it'll be awkwardly tall compared to Cover My Meds. A horizontal logo containing the text "Freenome" (like the ones on the shirt) would be the same height and give both companies the same name branding on the page.

**Comment by thomasrussellmurphy** [comment]
n.b. the code for rendering logos currently normalizes only the height of the image. Previous years have had pretty consistent rectangular logo+name "banner" images for each company.

**Comment by ramon349** [comment]
@JDulin  Changed it to the svg but could i get a  version of the logo  with the name of the company?

**Comment by JDulin** [comment]
Ah, I see - Excuse me. Ramon, you should have an email with what you need.  Thanks guys!

**Pull request merged**
